services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    secrets:
      - config_credentials
      - config_db
      - config_db_root
    volumes:
      - /home/$USER/data/wordpress/:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress 
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/ 
    secrets:
      - config_credentials
      - config_db
      - config_db_root
    env_file:
      - .env  
    volumes:
      - /home/$USER/data/lib/:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/ 
    secrets:
      - config_credentials
      - config_db
      - config_db_root
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
    env_file:
      - .env  
    networks:
      - inception
    depends_on:
          - mariadb
    restart: unless-stopped
networks:
  inception:
    driver: bridge

secrets:
  config_credentials:
    file: ../secrets/credentials.txt 
  config_db:
    file: ../secrets/db_password.txt
  config_db_root:
    file: ../secrets/db_rootpassword.txt
