services:
  nginx:
    build: ./srcs/requirements/nginx/ 
    volumes:
      - ./srcs/requirements/wordpress/tools/site/:/var/www/html
    ports:
      - 80:80
    depends_on:
      - wordpress 
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/ 
    env_file:
      - .env  
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - 3306:3306 
  wordpress:
    build: ./srcs/requirements/wordpress/ 
    container_name: wordp
    volumes:
      - ./srcs/requirements/wordpress/tools/site/:/var/www/html 
    env_file:
      - .env  
    ports:
      - 9000:9000
    networks:
      - inception
    depends_on:
          - mariadb
networks:
  inception:
    driver: bridge
