services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/ 
    volumes:
      - /home/$USER/data/wordpress/:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress 
  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/ 
    env_file:
      - .env  
    volumes:
      - /home/$USER/data/lib/:/var/lib/mysql
    ports:
      - 9000:9000
    networks:
      - inception
  wordpress:
    build: ./srcs/requirements/wordpress/ 
    container_name: wordpress
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
    env_file:
      - .env  
    networks:
      - inception
    depends_on:
          - mariadb
networks:
  inception:
    driver: bridge
